language: java

git:
  depth: 3

services:
  - docker

install: true

before_install:
- docker pull railflow/railflow:2.0.6
- docker run -d railflow/railflow:2.0.6 /bin/sh -c "cd /usr/railflow"

script:
- mvn clean test || true
- ls .
- cp ./testng-results.xml /usr/railflow
- npx railflow -k $RAILFLOW_KEY -url https://testrail6.railflow.io/ -u $RAILFLOW_USERNAME -p $RAILFLOW_PASSWORD -pr "Github-Demo" -path Demo/TestNG -f testng -r /usr/railflow/testng-results.xml -tp TestPlanName

