---
version: 2.1
orbs:
  railflow: railflow/railflow-orb@0.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      # run tests!
      - run: mvn clean test || true
      - run: ls .
      - store_artifacts:
          path: ./target/surefire-reports/testng-results.xml

  railflow_test:
    docker:
      - image: railflow/railflow:2.0.6

    working_directory: /usr/railflow
    steps:
      - run:
          name: download artifacts
          command: |
            curl -H "Circle-Token: $CIRCLE_TOKEN" https://circleci.com/api/v1.1/project/github/railflow/testng_example/10/artifacts \
            | grep -o 'https://[^"]*' \
            | wget --verbose --header "Circle-Token: $CIRCLE_TOKEN" --input-file -
      - run:
          name: Run railflow testing
          command: npx railflow -k $RAILFLOW_KEY -url https://testrail6.railflow.io/ -u $RAILFLOW_USERNAME -p $RAILFLOW_PASSWORD -pr "Github-Demo" -path Demo/TestNG -f testng -r /usr/railflow/testng-results.xml -tp TestPlanName

  railflow_orb_test:
    working_directory: /usr/railflow
    executor: railflow/default
    shell: /bin/bash --login -o pipefail
    environment:
      RAILFLOW_KEY: $RAILFLOW_KEY
      RAILFLOW_URL: https://testrail6.railflow.io/
      RAILFLOW_USERNAME: $RAILFLOW_USERNAME
      RAILFLOW_PASSWORD: $RAILFLOW_PASSWORD
      RAILFLOW_PROJECT_NAME: Github-ORB-Demo
      RAILFLOW_PROJECT_PATH: Demo/TestNG
      RAILFLOW_REPORT_FORMAT: testng
      RAILFLOW_REPORT_PATH: /usr/railflow/testng-results.xml
      RAILFLOW_SEARCH_MODE: path
      RAILFLOW_TEST_PLAN: OrbTestPlanName
      RAILFLOW_TEST_RUN: tr_testrun
      RAILFLOW_ASSIGN_FAILURE_TO: redcom@gmail.com
    steps:
      - railflow/test:
          RAILFLOW_KEY: $RAILFLOW_KEY
          RAILFLOW_URL: $RAILFLOW_URL
          RAILFLOW_USERNAME: $RAILFLOW_USERNAME
          RAILFLOW_PASSWORD: $RAILFLOW_PASSWORD
          RAILFLOW_PROJECT_NAME: $RAILFLOW_PROJECT_NAME
          RAILFLOW_PROJECT_PATH: $RAILFLOW_PROJECT_PATH
          RAILFLOW_REPORT_FORMAT: $RAILFLOW_REPORT_FORMAT
          RAILFLOW_REPORT_PATH: $RAILFLOW_REPORT_PATH
          RAILFLOW_SEARCH_MODE: $RAILFLOW_SEARCH_MODE
          RAILFLOW_TEST_PLAN: $RAILFLOW_TEST_PLAN
          RAILFLOW_TEST_RUN: $RAILFLOW_TEST_RUN
          RAILFLOW_ASSIGN_FAILURE_TO: $RAILFLOW_ASSIGN_FAILURE_TO
      - run:
          name: Run railflow testing
          command: |
            echo -e "\n$RAILFLOW_KEY\n$RAILFLOW_USERNAME\n$RAILFLOW_PASSWORD" > testsetup && cat testsetup

      - store_artifacts:
          path: $RAILFLOW_REPORT_PATH
          destination: railflow-artifacts
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - development
      - railflow_test:
          requires:
            - build
  pull_request:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - main
      - railflow_test:
          requires:
            - build
      - railflow_orb_test:
          requires:
            - build

