version: 2
jobs:
  railflow_test:
    docker:
      - image: railflow/railflow:2.0.6

    working_directory: /usr/railflow
    steps:
      - run: ls .
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      # run tests!
      - run: mvn clean test || true
      - run: ls .
      - store_artifacts:
          path: ./target/surefire-reports/testng-results.xml
